version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: techrs
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
