export namespace Constants {
  export const SEQUELIZE = 'SEQUELIZE';
  export const USERS_REPOSITORY = 'USERS_REPOSITORY';
  export const SUPPLY_CATEGORIES_REPOSITORY = 'SUPPLY_CATEGORIES_REPOSITORY';
  export const SUPPLIES_REPOSITORY = 'SUPPLIES_REPOSITORY';
  export const SHELTERS_REPOSITORY = 'SHELTERS_REPOSITORY';
  export const SHELTERS_SUPPLIES_REPOSITORY = 'SHELTERS_SUPPLIES_REPOSITORY';
  export const ALERTS_REPOSITORY = 'ALERTS_REPOSITORY';
  export const ADDRESSES_REPOSITORY = 'ADDRESSES_REPOSITORY';
}
