name: Full Prod
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: "Get image tags"
        id: image-tags
        run: |
          echo "specific=vanflux/bc-api:$(date +'%Y-%m-%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "latest=vanflux/bc-api:latest" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.image-tags.outputs.specific }},${{ steps.image-tags.outputs.latest }}
